model_params:
  in_channels: 47640
  latent_dim: 256

dataset_params:
  directory: "experiment/VAE/data/AAL2_data/angry_residual_AAL2"

dataloader_params:
  batch_size: 64
  num_workers: 10
  pin_memory: True

exp_params:
  LR: 0.0001
  weight_decay: 0.00001
  kld_weight: 0.0002
  manual_seed: 100
  global_epoch: 500
  scheduler: True
  warmup_iter: None
  cosine_Tmax: 5

trainer_params:
  gpus: [1]
  max_epochs: 500

logging_params:
  save_dir: "experiment/VAE/result/"
  modelname: "VectorVAE"
  idname: "cv_id.json"


